import { Download, FileJson, FileText } from 'lucide-react';
import type { PipelineRecord } from '../types/pipeline';

interface SpecPanelProps {
  record?: PipelineRecord;
  onExportMarkdown: () => void;
  onExportJson: () => void;
}

export function SpecPanel({ record, onExportMarkdown, onExportJson }: SpecPanelProps) {
  if (!record) {
    return (
      <section className="rounded-lg border border-dashed border-ink-300 bg-white p-8 text-center dark:border-ink-700 dark:bg-ink-900">
        <p className="text-sm text-ink-500 dark:text-ink-400">
          Generate or reopen a design to inspect the architecture, workflow, and recommendations.
        </p>
      </section>
    );
  }

  const spec = record.spec;

  return (
    <section className="rounded-lg border border-ink-200 bg-white dark:border-ink-800 dark:bg-ink-900">
      <div className="flex flex-col gap-3 border-b border-ink-200 p-4 dark:border-ink-800 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0">
          <h2 className="break-words text-xl font-semibold">{spec.title}</h2>
          <p className="mt-1 text-sm leading-6 text-ink-600 dark:text-ink-300">
            {spec.summary}
          </p>
          <p className="mt-2 text-xs text-ink-500 dark:text-ink-400">
            Generated by {spec.generated_by}
          </p>
        </div>
        <div className="flex shrink-0 flex-wrap gap-2">
          <button
            type="button"
            onClick={onExportMarkdown}
            className="inline-flex h-9 items-center gap-2 rounded-lg border border-ink-200 px-3 text-sm font-medium hover:bg-ink-100 dark:border-ink-700 dark:hover:bg-ink-800"
          >
            <FileText size={16} />
            Markdown
          </button>
          <button
            type="button"
            onClick={onExportJson}
            className="inline-flex h-9 items-center gap-2 rounded-lg border border-ink-200 px-3 text-sm font-medium hover:bg-ink-100 dark:border-ink-700 dark:hover:bg-ink-800"
          >
            <FileJson size={16} />
            JSON
          </button>
        </div>
      </div>

      {spec.generation_warnings.length > 0 ? (
        <div className="border-b border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-200">
          {spec.generation_warnings.join(' ')}
        </div>
      ) : null}

      <div className="grid gap-4 p-4 xl:grid-cols-[1fr_360px]">
        <div className="space-y-5">
          <Block title="Architecture">
            <p>{spec.architecture}</p>
          </Block>

          <Block title="ETL Workflow">
            <div className="space-y-3">
              {spec.workflow
                .slice()
                .sort((a, b) => a.order - b.order)
                .map((step) => (
                  <div
                    key={`${step.order}-${step.name}`}
                    className="rounded-lg border border-ink-200 p-3 dark:border-ink-800"
                  >
                    <div className="flex gap-3">
                      <span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-signal-100 text-xs font-semibold text-signal-700 dark:bg-signal-950 dark:text-signal-100">
                        {step.order}
                      </span>
                      <div className="min-w-0">
                        <p className="font-semibold">{step.name}</p>
                        <p className="mt-1 text-sm leading-6 text-ink-600 dark:text-ink-300">
                          {step.description}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
            </div>
          </Block>

          <Block title="AWS Services">
            <div className="grid gap-3 md:grid-cols-2">
              {spec.aws_services.map((service) => (
                <div
                  key={`${service.name}-${service.category}`}
                  className="rounded-lg border border-ink-200 p-3 dark:border-ink-800"
                >
                  <div className="flex items-start justify-between gap-3">
                    <p className="font-semibold">{service.name}</p>
                    <span className="rounded-md bg-ink-100 px-2 py-1 text-xs text-ink-600 dark:bg-ink-800 dark:text-ink-300">
                      {service.category}
                    </span>
                  </div>
                  <p className="mt-2 text-sm leading-6 text-ink-600 dark:text-ink-300">
                    {service.purpose}
                  </p>
                  <p className="mt-2 text-sm leading-6 text-ink-500 dark:text-ink-400">
                    {service.why_selected}
                  </p>
                </div>
              ))}
            </div>
          </Block>

          <Block title="Folder Structure">
            <pre className="overflow-auto rounded-lg bg-ink-950 p-4 text-xs leading-6 text-ink-100">
              {spec.folder_structure}
            </pre>
          </Block>
        </div>

        <aside className="space-y-4">
          <Recommendation title="Ingestion" body={spec.ingestion_strategy.rationale} />
          <Recommendation title="Storage" body={spec.storage_layer.rationale} />
          <Recommendation title="Transformation" body={spec.transformation_layer.rationale} />
          <Recommendation title="Orchestration" body={spec.orchestration_strategy.rationale} />
          <Recommendation title="Monitoring" body={spec.monitoring_strategy.rationale} />
          <ListBlock title="Security" items={spec.security_best_practices} />
          <ListBlock title="Cost Optimization" items={spec.cost_optimization} />
          <ListBlock title="Deployment" items={spec.deployment_recommendations} icon={<Download size={16} />} />
          <ListBlock title="Risks" items={spec.risks} />
        </aside>
      </div>
    </section>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="mb-2 text-sm font-semibold uppercase tracking-normal text-ink-500 dark:text-ink-400">
        {title}
      </h3>
      <div className="text-sm leading-6 text-ink-700 dark:text-ink-200">{children}</div>
    </div>
  );
}

function Recommendation({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-lg border border-ink-200 p-3 dark:border-ink-800">
      <h3 className="text-sm font-semibold">{title}</h3>
      <p className="mt-2 text-sm leading-6 text-ink-600 dark:text-ink-300">{body}</p>
    </div>
  );
}

function ListBlock({
  title,
  items,
  icon,
}: {
  title: string;
  items: string[];
  icon?: React.ReactNode;
}) {
  return (
    <div className="rounded-lg border border-ink-200 p-3 dark:border-ink-800">
      <div className="flex items-center gap-2">
        {icon}
        <h3 className="text-sm font-semibold">{title}</h3>
      </div>
      <ul className="mt-2 space-y-2 text-sm leading-6 text-ink-600 dark:text-ink-300">
        {items.map((item) => (
          <li key={item} className="flex gap-2">
            <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-signal-600" />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
